### ISSUE TITLE
Feature Request - Substitute Holidays

### ISSUE THREAD

**Issue by yarosz** [jonstuebe/date-fns-holiday-us#6]
Would be nice to have the option, particularly when using  getBankHolidays, to return substitute holidays. Substitutes for holidays falling on Saturday are on the preceding Friday and for holidays falling on Sundays are on the following Monday. ([source](https://www.federalreserve.gov/aboutthefed/k8.htm))

i.e. In 2021, Independence Day's substitute would be Monday July 5 and Christmas Day's Substitute would be Friday, December 24.

**Comment by jonstuebe** [comment]
Love this. I think it's called something like an "observed" holiday right? I'll see if I can work on this sometime soon!

**Comment by jonstuebe** [comment]
closed by #20
